pregunta_datos = [
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano", "dificultad": "media",
     "pregunta": "El estándar HTML5 se publicó en 2014.",
     "respuesta_correcta": "Verdadero",
     "respuestas_incorrectas": ["Falso"]},
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano",
     "dificultad": "media",
     "pregunta": "El acrónimo común de programación de software &quot;I18N&quot; "
                 "viene del término &quot;Interlocalización&quot;.",
     "respuesta_correcta": "Falso", "respuestas_incorrectas": ["Verdadero"]},
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano",
     "dificultad": "media",
     "pregunta": "El primer error informático se formó por cables defectuosos.",
     "respuesta_correcta": "Falso",
     "respuestas_incorrectas": ["Verdadero"]},
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano",
     "dificultad": "media",
     "pregunta": "FLAC significa &quot;Condensador de audio sin pérdida libre&quot;#039;",
     "respuesta_correcta": "Falso",
     "respuestas_incorrectas": ["Verdadero"]},
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano",
     "dificultad": "media",
     "pregunta": "El primer &quot;error&quot; registrado en una computadora fue una polilla que se encontró dentro"
                 " de una computadora Harvard Mark II.",
     "respuesta_correcta": "Verdadero",
     "respuestas_incorrectas": ["Falso"]},
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano", "dificultad": "media",
     "pregunta": "Todos los códigos de programa deben compilarse en un archivo ejecutable para poder ejecutarse."
                 "Este archivo se puede ejecutar en cualquier máquina.",
     "respuesta_correcta": "Falso",
     "respuestas_incorrectas": ["Verdadero"]},
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano",
     "dificultad": "media",
     "pregunta": "&quot;Windows NT&quot; es un núcleo monolítico.",
     "respuesta_correcta": "Falso",
     "respuestas_incorrectas": ["Verdadero"]},
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano",
     "dificultad": "media",
     "pregunta": "Para eludir las leyes de exportación de municiones de EE. UU., el creador de PGP publicó todo el"
                 " código fuente en un libro",
     "respuesta_correcta": "Verdadero",
     "respuestas_incorrectas": ["Falso"]},
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano",
     "dificultad": "media",
     "pregunta": "MacOS está basado en Linux.",
     "respuesta_correcta": "Falso",
     "respuestas_incorrectas": ["Verdadero"]},
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano",
     "dificultad": "media",
     "pregunta": "El programa de código abierto Redis es un servidor de base de datos relacional.",
     "respuesta_correcta": "Falso",
     "respuestas_incorrectas": ["Verdadero"]},
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano",
     "dificultad": "media",
     "pregunta": "La primera CPU de doble núcleo fue Intel Pentium D.",
     "respuesta_correcta": "Falso",
     "respuestas_incorrectas": ["Verdadero"]},
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano",
     "dificultad": "media",
     "pregunta": "No es posible formatear un disco duro DVD-R protegido contra escritura.",
     "respuesta_correcta": "Verdadero",
     "respuestas_incorrectas": ["Falso"]},
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano",
     "dificultad": "media",
     "pregunta": "Las versiones de Android se nombran en orden alfabético.",
     "respuesta_correcta": "Verdadero",
     "respuestas_incorrectas": ["Falso"]},
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano",
     "dificultad": "media",
     "pregunta": "Linus Sebastian es el creador del kernel de Linux, que luego se usó en Linux, Android, "
                 "y sistema operativo Chrome.",
     "respuesta_correcta": "Falso",
     "respuestas_incorrectas": ["Verdadero"]},
    {"categoría": "Ciencia: Informática",
     "tipo": "booleano",
     "dificultad": "media",
     "pregunta": "Un valor booleano de &quot;0&quot; representa ¿cuál de estas palabras?",
     "respuesta_correcta": "Falso",
     "respuestas_incorrectas": ["Verdadero"]}
]
